#!/bin/bash
python utils/prototype.py --save_path results/hyperlex/PROTOTYPE_KDE.txt --entailment --method kde
python utils/prototype.py --save_path results/hyperlex/PROTOTYPE_KDE_DBSCAN.txt --entailment --dbscan --method kde
